[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Abhishek Ranjan <abhishek.ranjan@sprouts.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
